version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinematch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: fastapi_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cinematch
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: streamlit_frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"

  model-service:
    build:
      context: ./model-service
      dockerfile: Dockerfile
    container_name: model_service
    ports:
      - "8001:8001"

volumes:
  postgres_data:
  
