name:  CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start full system (docker compose)
        run: |
          docker compose -f docker-compose.db_included.yml up -d --build

      - name: Wait for services to be ready
        run: sleep 60

      - name: Install test dependencies
        run: pip install pytest requests

      - name: Run integration tests
        run: pytest -q

      - name: Shutdown system
        if: always()
        run: docker compose down -v
